spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: xiaonaimao
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.computacenter: info
  file:
    path: log/contact-pro.log

server:
  port: 8082
