name: Deploy to Heroku

on:
  push:
    branches:
      - deployOnHeroku
  pull_request:
    branches:
      - deployOnHeroku


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "contact-app-weijia" #Must be unique in Heroku
          heroku_email: "ivanaluo1994@gmail.com"
          branch: "deployOnHeroku"
          justlogin: true
  
      - name: Deploy to Heroku
      - run: |
          heroku auth:whoami
          heroku git:remote -a contact-app-weijia
          git fetch --all
          git pull
          git push heroku deployOnHeroku:master

          




